# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    # for self-hosted:
    # runs-on: [self-hosted, linux, X64]
    strategy:
      matrix:
        python-version: [3.9.12]
    services:
      mqtt:
        image: eclipse-mosquitto:2.0
        ports:
          - "1883:1883"
        volumes:
          - ./mosquitto/config:/mosquitto/config
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: | 
        python -m pip install --upgrade pip
        pip --version
    - name: Print environment
      run: |
        env
    - name: Install dependencies
      run: |
        pip install -r requirements/local.txt
        pip install -e .
    
    - name: Docker-compose Build
      run: docker-compose up -d --build
    - name: Docker-compose list containers
      run: docker-compose ps
    
    - name: Run black --check .
      run: black --check . --exclude _actions
    - name: Test with pytest
      run: |
        cd unittests
        pytest

